### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by jdrieghe** [matthiasnoback/broadway-serialization#13]
Since `broadway/broadway 2.4` supports PHP 8, it might be useful to update this library as well.

I experimented a little bit already and it seems fairly straightforward except for 1 thing: the Symfony integration.

What strategy should we apply going forward?
My suggestion would be to remove the Symfony integration and rely on the framework independent configuration for this library moving forward. Additional libraries can easily be created to integrate with different frameworks, but as the configuration is just a couple of lines I'm not sure if it's worth it.

I would be happy to submit a PR that updates dev dependencies and adds PHP8 compatibility.

**Comment by matthiasnoback** [comment]
Agreed. I'm not sure how many projects are actually using this library anyway It has to be a major release in that case. So please feel free to modernize other aspects as well.

**Comment by jdrieghe** [comment]
Step 1: https://github.com/matthiasnoback/broadway-serialization/pull/14

**Comment by jdrieghe** [comment]
> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com.

I think this would be a good reason to migrate the CI pipeline to Github Actions

**Comment by matthiasnoback** [comment]
Nice work! I added the migration to GitHub Actions. I'll release a version 3.0 now.

**Comment by matthiasnoback** [comment]
Also, @jdrieghe, feel free to make other PRs if this library needs to be updated according to modern standards. If you like you could also become a maintainer and go ahead with this project.
