### ISSUE TITLE
Add deserialization for DateTime objects

### ISSUE THREAD

**Issue by Konafets** [matthiasnoback/broadway-serialization#3]
DT objects will serialize to 

`[
    "date": "2016-02-17 12:26:05.389122",
    "timezone_type": 1,
    "timezone": "+00:00"
]
`

and should deserialized automatically to a DT object again.

**Comment by matthiasnoback** [comment]
I think this is too specific to become a standard part of this library.

You can treat a `DateTime` object just like any other object or wrap it in a custom object (with `serialize()` and `deserialize()` methods) if you like.

**Comment by Konafets** [comment]
Do you have an example of 

> You can treat a DateTime object just like any other object? 

How do I get an DateTime object back from deserialization?

**Comment by matthiasnoback** [comment]
Well, if the `DateTime` object isn't the main object you're serializing, you can just convert it to and from a string in the main object's `serialize()`/`deserialize()` methods, right?
Anyway, if you like to use this library for automatic serialization deserialization it might be simpler to create your own DateTime-like object which wraps the PHP one.

**Comment by Konafets** [comment]
> Well, if the DateTime object isn't the main object you're serializing, you can just convert it to and from a string in the main object's serialize()/deserialize() methods, right?

This is not working when I already use `deserializationCallbacks()` in the main class. 

> Anyway, if you like to use this library for automatic serialization deserialization it might be simpler to create your own DateTime-like object which wraps the PHP one.

This was the only option I came up with but it feels wrong to create another custom type just for (de)serialization.

**Comment by matthiasnoback** [comment]
Ah, I see what you mean. Yes, but the callback can also be just an inline `function() {}`, so you can move the code inside it.

**Comment by Konafets** [comment]
Sorry, I don't get it. Can you provide an example?

```
/**
 * Deserialize the object
 */
protected static function deserializationCallbacks()
{
    return [
        'foo' => [Foo::class, 'deserialize'],
        'bar' => [Bar::class, 'deserialize'],
        'date' => ???,
    ];
}
```

**Comment by matthiasnoback** [comment]
Something like: 

```
/**
 * Deserialize the object
 */
protected static function deserializationCallbacks()
{
    return [
        'foo' => [Foo::class, 'deserialize'],
        'bar' => [Bar::class, 'deserialize'],
        'date' => function($value) { return \DateTime::createFromFormat('...', $value); }
    ];
}
```

**Comment by Konafets** [comment]
Thanks!
